version: '3.9'
services:
  db:
    image: mongo
    container_name: test-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_URL=mongodb://admin:pass@db:27017/
    depends_on:
      - db

  fetcher:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile.fetcher
    container_name: fetcher
    ports:
     - 9090:9090
    environment:
      HTTP_ADDR: ":9090"
      MONGODB: "mongodb://admin:pass@db:27017/"
      FETCH_URL: "https://www.htafc.com/api/incrowd/getnewlistinformation?count=50"
    

